### ISSUE TITLE
This actions is not reporting good coverage for me

### ISSUE THREAD

**Issue by boly38** [Tintef/nyc-reporter-action#1]
After multiple attempts, this action had push a comment on my PR:
![image](https://user-images.githubusercontent.com/3100576/110210633-d2afe580-7e92-11eb-90a8-f5c2e504074e.png)

Here is my github action yml configuration extract : 
```
   # https://github.com/Tintef/nyc-reporter-action
    - name: NYC Coverage Report
      uses: Tintef/nyc-reporter-action@0.1.0
      with:
        GITHUB_TOKEN: ${{ secrets.NYC_COVERAGE_TOKEN }}
        REPORTER: 'text' # defaults to 'text-summary'
```
Please notice that your readme sample doesn't include version (and uppercase for first letter?) and dont work without (at least version)

---

Locally on my private project, if  run coverage then the following
```
$ npx nyc report -t ./coverage/
----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |
----------|---------|----------|---------|---------|-------------------

```

If I'm doing the same without `-t` option, then I got the report

```
$ npx nyc report
---------------------------|---------|----------|---------|---------|-------------------------------
File                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
---------------------------|---------|----------|---------|---------|-------------------------------
All files                  |   64.72 |    54.86 |   62.78 |   65.23 |
(...)
```

- is `-t` option mandatory ?
- could you make an option to avoid adding `-t`?

Thanks

NB/ I just switch onto `romeovs/lcov-reporter-action@v0.2.16`  which work but doesn't remove previous report too
