### ISSUE TITLE
`ENOENT: no such file or directory, scandir`

### ISSUE THREAD

**Issue by nilsreichardt** [Tintef/nyc-reporter-action#2]
```yml
    - name: Coverage
      uses: tintef/nyc-reporter-action@0.2.5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WORKING_DIRECTORY: ${{ env.WORKING_DIRECTORY }}
```

```
Run tintef/nyc-reporter-action@0.2.5
/usr/local/bin/npx nyc report --reporter=text-summary -t coverage --cwd infrastructure/google_cloud_platform/firebase/cloud_functions/typescript_cloud_functions/functions
npx: installed 147 in 5.314s
ENOENT: no such file or directory, scandir '/home/runner/work/myProject/myProject/infrastructure/google_cloud_platform/firebase/cloud_functions/typescript_cloud_functions/functions/coverage'
Error: The process '/usr/local/bin/npx' failed with exit code 1
```
